alias jsc='cd ~/dev/JSCover'
alias jscmt='cd ~/dev/JSCover-maven-test'
alias jscmp='cd ~/dev/JSCover-maven-plugin'
alias jscs='cd ~/dev/JSCover-samples'

alias sgb='cd ~/dev/SG/SG-git/build'
alias sgstart='~/dev/SG/solr-9.9.0/bin/solr start -p 8984;nohup java -Xmx64m -jar fakeSMTP-2.1-SNAPSHOT.jar &'
alias sgstop='~/dev/SG/solr-9.9.0/bin/solr stop'
alias s8start='~/dev/SG/solr-8.11.3/bin/solr start'
alias s8stop='~/dev/SG/solr-8.11.3/bin/solr stop'
#alias bloff='echo 0 | sudo tee /sys/devices/platform/sony-laptop/kbd_backlight'
#alias blon='echo 1 | sudo tee /sys/devices/platform/sony-laptop/kbd_backlight'
#alias vboxdrv='sudo modprobe vboxdrv'
#alias rboxdrv='sudo /sbin/rcvboxdrv setup'
