alias jsc='cd ~/dev/JSCover'
alias jscmt='cd ~/dev/JSCover-maven-test'
alias jscmp='cd ~/dev/JSCover-maven-plugin'
alias jscs='cd ~/dev/JSCover-samples'

alias sgb='cd ~/dev/SG/SG-git/build'
alias sgstart='~/dev/SG/solr-5.4.1/bin/solr start;nohup java -Xmx64m -jar fakeSMTP-2.0.jar &'
alias sgstop='~/dev/SG/solr-5.4.1/bin/solr stop'
#alias bloff='echo 0 | sudo tee /sys/devices/platform/sony-laptop/kbd_backlight'
#alias blon='echo 1 | sudo tee /sys/devices/platform/sony-laptop/kbd_backlight'
#alias vboxdrv='sudo modprobe vboxdrv'
#alias rboxdrv='sudo /sbin/rcvboxdrv setup'
