alias jsc='cd ~/dev/JSCover'
alias jsc2='cd ~/dev/JSCover2'
alias jscmt='cd ~/dev/JSCover-maven-test'
alias jscmp='cd ~/dev/JSCover-maven-plugin'
alias jscs='cd ~/dev/JSCover-samples'
alias jscr='cd ~/dev/rhino-jscover'
alias jscrr='cd ~/dev/rhino-jscover-repackaged'
alias jmon='cd ~/dev/JMonitaur'
alias up='cd ~/dev/update-projects;./update.sh'
alias j7='JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64;export PATH=$JAVA_HOME/bin:$PATH'

alias ij='nohup /usr/share/idea-IU-139.659.2/bin/idea.sh &'
alias ij14='nohup /usr/share/idea-IU-139.224.1/bin/idea.sh &'
alias ij13='nohup /usr/share/idea-IU-135.909/bin/idea.sh &'

alias sgb='cd ~/dev/SG/SG-svn/build'
alias sggb='cd ~/dev/SG/SG-git/build'
alias astart='sudo ~/dev/SG/apache2/bin/apachectl start'
alias astop='sudo ~/dev/SG/apache2/bin/apachectl stop'
alias bloff='echo 0 | sudo tee /sys/devices/platform/sony-laptop/kbd_backlight'
alias blon='echo 1 | sudo tee /sys/devices/platform/sony-laptop/kbd_backlight'
